package_assets: on
embed_assets: on
javascript_compressor: closure

javascripts:
  default:
    - public/javascripts/jquery-1.5.2.js
    - public/javascripts/jquery.*.js
    - public/javascripts/rails.js
    - public/javascripts/markitup-markdown.js
    - public/javascripts/dlfp.*.js
    - public/javascripts/application.js

stylesheets:
  default:
    - public/stylesheets/RonRonnement.css
  mobile:
    - public/stylesheets/contrib/grayscale.css
    - public/stylesheets/mobile.css
  print:
    - public/stylesheets/print.css
